services:
  mirakurun:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: chinachu/mirakurun:latest
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      DOCKER_NETWORK: host
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    network_mode: host
    # comment out `devices:` if you commented out all devices
    # device を全てコメントアウトした場合は devices: もコメントアウト
    devices:
      # comment out below if you don't use card readers
      # カードリーダーを使わない場合は以下をコメントアウト
      - /dev/bus:/dev/bus
      # comment out below if you don't use DVB devices
      # DVB チューナーを使わない場合は以下をコメントアウト
      - /dev/dvb:/dev/dvb
    volumes:
      # you can change to any location if you want.
      - type: bind
        source: /opt/mirakurun/run
        target: /var/run
        bind:
          create_host_path: true
      - type: bind
        source: /opt/mirakurun/opt
        target: /opt
        bind:
          create_host_path: true
      - type: bind
        source: /opt/mirakurun/config
        target: /app-config
        bind:
          create_host_path: true
      - type: bind
        source: /opt/mirakurun/data
        target: /app-data
        bind:
          create_host_path: true
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
